In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
import tensorflow.keras as keras
from tensorflow.keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img
import cv2
import joblib

In [2]:
path = "D:/Image_data/0/Leonardite (1).jpg"

In [9]:
img = cv2.imread(path)
img = cv2.resize(img, (32, 32), interpolation=cv2.INTER_NEAREST)
img = np.float32(img)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
img = cv2.rotate(img, cv2.ROTATE_180)
img = img/255.0

In [7]:
img_2 = keras.utils.load_img((path), target_size=(32, 32))
# img = np.float32(img)
# img = img/255.0

In [8]:
type(img_2)

PIL.Image.Image

In [6]:
np.float32(img)/255.0

array([[[0.49019608, 0.42745098, 0.3764706 ],
        [0.48235294, 0.41960785, 0.36862746],
        [0.49019608, 0.4392157 , 0.3764706 ],
        ...,
        [0.47843137, 0.42745098, 0.36078432],
        [0.48235294, 0.43137255, 0.3647059 ],
        [0.47058824, 0.42745098, 0.35686275]],

       [[0.49019608, 0.43529412, 0.38431373],
        [0.4862745 , 0.44705883, 0.40784314],
        [0.53333336, 0.5058824 , 0.4745098 ],
        ...,
        [0.63529414, 0.6431373 , 0.6392157 ],
        [0.67058825, 0.6784314 , 0.6666667 ],
        [0.6627451 , 0.67058825, 0.65882355]],

       [[0.68235296, 0.6862745 , 0.69411767],
        [0.69411767, 0.69803923, 0.7058824 ],
        [0.68235296, 0.69803923, 0.7019608 ],
        ...,
        [0.6784314 , 0.6862745 , 0.68235296],
        [0.6745098 , 0.68235296, 0.67058825],
        [0.6745098 , 0.68235296, 0.67058825]],

       ...,

       [[0.654902  , 0.67058825, 0.6745098 ],
        [0.65882355, 0.6745098 , 0.6784314 ],
        [0.6666667 , 0

In [11]:
img

array([[[0.5019608 , 0.4392157 , 0.38039216],
        [0.5058824 , 0.45490196, 0.39215687],
        [0.49803922, 0.44705883, 0.38431373],
        ...,
        [0.6392157 , 0.64705884, 0.6431373 ],
        [0.6509804 , 0.65882355, 0.654902  ],
        [0.6156863 , 0.62352943, 0.6117647 ]],

       [[0.6745098 , 0.6901961 , 0.69411767],
        [0.6784314 , 0.69411767, 0.69803923],
        [0.6784314 , 0.69411767, 0.69803923],
        ...,
        [0.6666667 , 0.6745098 , 0.6627451 ],
        [0.6666667 , 0.6745098 , 0.6627451 ],
        [0.6627451 , 0.67058825, 0.65882355]],

       [[0.6901961 , 0.69411767, 0.7019608 ],
        [0.6784314 , 0.69411767, 0.69803923],
        [0.6901961 , 0.7058824 , 0.70980394],
        ...,
        [0.67058825, 0.6784314 , 0.6666667 ],
        [0.6745098 , 0.68235296, 0.67058825],
        [0.6627451 , 0.67058825, 0.65882355]],

       ...,

       [[0.654902  , 0.67058825, 0.6745098 ],
        [0.6666667 , 0.68235296, 0.6862745 ],
        [0.65882355, 0

In [23]:
img_2

array([[[0.5019608 , 0.4392157 , 0.38039216],
        [0.5058824 , 0.45490196, 0.39215687],
        [0.49803922, 0.44705883, 0.38431373],
        ...,
        [0.6392157 , 0.64705884, 0.6431373 ],
        [0.6509804 , 0.65882355, 0.654902  ],
        [0.6156863 , 0.62352943, 0.6117647 ]],

       [[0.6745098 , 0.6901961 , 0.69411767],
        [0.6784314 , 0.69411767, 0.69803923],
        [0.6784314 , 0.69411767, 0.69803923],
        ...,
        [0.6666667 , 0.6745098 , 0.6627451 ],
        [0.6666667 , 0.6745098 , 0.6627451 ],
        [0.6627451 , 0.67058825, 0.65882355]],

       [[0.6901961 , 0.69411767, 0.7019608 ],
        [0.6784314 , 0.69411767, 0.69803923],
        [0.6901961 , 0.7058824 , 0.70980394],
        ...,
        [0.67058825, 0.6784314 , 0.6666667 ],
        [0.6745098 , 0.68235296, 0.67058825],
        [0.6627451 , 0.67058825, 0.65882355]],

       ...,

       [[0.654902  , 0.67058825, 0.6745098 ],
        [0.6666667 , 0.68235296, 0.6862745 ],
        [0.65882355, 0

In [20]:
pd.Series((np.reshape(img_2, (-1))) == (np.reshape(img, (-1)))).value_counts()

True    3072
dtype: int64